#!/bin/bash
echo -- `cat swagger.json`

VERSION=${TRAVIS_TAG:-${TAG_NAME:-dev}}

docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local swaggerapi/swagger-codegen-cli:v2.3.0\
           generate -i /local/swagger.json\
           --git-user-id rienafairefr\
           --git-repo-id pynYNAB\
           -l python -o /local/ynab-api -DprojectName=ynab_api -DpackageName=ynab_api\
           -DpackageVersion="$VERSION" -DappDescription="This is an autogenerated package to access\
           api.youneedabudget.com using its swagger spec"
